### ISSUE TITLE
OnePlus 7 Pro 8/256, USB Driver not working

### ISSUE THREAD

**Issue by EvoSlime** [woa-msmnile/OnePlus#2]
When Windows start i'm getting bsod with error "fsa4480.sys"
after remove this driver windows start fine but usb doesn't work, only charging

**Comment by nyveZz** [comment]
same device and same issue
not sure if charging works tho (i believe it only shows an indicator but actually doesn't charge)

**Comment by jorbig** [comment]
USB is not important for me, but charging is. Can someone confirm if it charges (maybe just enough to keep the device running)?

**Comment by nyveZz** [comment]
> USB is not important for me, but charging is. Can someone confirm if it charges (maybe just enough to keep the device running)?

for me no, the indicator shows up but it doesn't charge (oneplus 7 pro)
on the oneplus 7t pro it will probably work
if you want to buy a device just to run windows consider one of the sd845 devices

**Comment by NetuserPRO** [comment]
fsa4480 is fixed. use usb host mode #5
